name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:
  build-and-test:

    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Build and Test
        run: xcodebuild clean build test -project InstagramFeedClone/InstagramFeedClone.xcodeproj -scheme "InstagramFeedClone" CODE_SIGN_IDENTITY="" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
        
        run: xcodebuild clean build test -workspace InstagramFeedCloneApp/InstagramFeedCloneApp.xcworkspace -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=18.2,name=iPhone 16 Pro" ONLY_ACTIVE_ARCH=YES

